name: EC2 Direct Deploy

on:
  push:
    branches: [main]      # deploy only from main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (needed only to satisfy actions/checkout)
        uses: actions/checkout@v4


      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     3.124.194.160
          username: ec2-user
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "▶ 1) Navigate to app dir"
            cd ~/REDacted

            echo "▶ 2) Pull latest code"
            git fetch origin main && git reset --hard origin/main

            echo "▶ 3) Stop & remove old container"
            docker stop redacted-container || true
            docker rm   redacted-container || true

            echo "▶ 4) Remove old image"
            docker rmi redacted || true

            echo "▶ 5) Build new image"
            docker build -t redacted .

            echo "▶ 6) Start container"
            cd app
            docker run -d \
              --restart unless-stopped \
              --env-file .env \
              -p 8000:8000 \
              --name redacted-container \
              redacted